### ISSUE TITLE
async generators?

### ISSUE THREAD

**Issue by k-tten** [maruseron/tinylazyseq#1]
what about async generators (using [Symbol.asyncIterator])?

i have a  use case/example:

```ts
declare function getTasks(): Promise<Task>[];

const seq = Sequence.of(await getTasks());

for (const task of seq) {
    ???
}

seq.forEach((task) => {
    ???
});

for await (const task of seq) {
    task // :D
}
```

**Comment by maruseron** [comment]
A bit confused here for a couple reasons - arrays are not awaitable and `Sequence#of` does not expect an iterable, but varargs with the literal elements contained by the Sequence.

That aside, `Sequence#from` will still not accept an AsyncIterable since Sequences weren't designed with AsyncIterables in mind, meaning currently there is _no_ support for AsyncIterables at all.

As a footnote, I have no idea how to reconcile the AsyncIterable API with the Iterable API - given they require inherently different metadata and are not compatible with each other (unless they overlap, which sounds like a recipe for spaghetti and/or an infinite source of bugs) - without making an entirely new `AsyncSequence` class that the Sequence factories delegate the asynchronous responsibilities to, and I worry that would defeat the point of "small library". Not saying I wouldn't; AsyncSequences do sound like a valid usecase and quite important - just rambling about the challenges of its implementation. Overall, this is a great idea - although bit more detail would certainly help -; thanks for the feedback.

**Comment by maruseron** [comment]
Making an update on this particular topic - doing some exploration of the issue (reconciling async and sync iterables) I came up a couple possible solutions, each with their own pros and cons:

### Not giving a f**k...?
For the sake of simplicity and specificity, two different `Sequence<T>` and `AsyncSequence<T>` classes could be made, incompatible with each other and unrelated through type, since doing so would make them uniterable. To better illustrate it:
```ts
class SyncSequence<T> implements Iterable<T> { /* ... */ }
class AsyncSequence<T> implements AsyncIterable<T> { /* ... */}

const mySeq = asSequence(someIterable);             // factories can't get any iterable,
const myASeq = asAsyncSequence(someAsyncIterable);  // since the sequences don't overlap
``` 
If we related them by type, the following problem would appear:
```ts
interface Sequence<T> { /* ... */ }
class SyncSequence<T> implements Sequence<T>, Iterable<T> { /* ... */ }
class AsyncSequence<T> implements Sequence<T>, AsyncIterable<T> { /* ... */ }

// factory method: returns an AsyncSequence casted to the interface
const mySeq: Sequence<number> = asSequence(asyncNumberGenerator());

for await (const num of mySeq) // compile error, Sequence<T> does not have an AsyncIterator method
```

### Relating them through type and adding helpers to allow `for` iteration
Following the problem above, this could be somewhat fixed by adding some extra methods to the Sequence interface, namely:
```ts
interface Sequence<T> { 
    /* ... sequence methods ... */
    isAsync(): this is AsyncSequence<T>;
    isSync(): this is SyncSequence<T>;
 }
class SyncSequence<T> implements Sequence<T>, Iterable<T> { /* ... */ }
class AsyncSequence<T> implements Sequence<T>, AsyncIterable<T> { /* ... */ }

const mySeq: Sequence<number> = returnsSomeSequence();

if (mySeq.isAsync()) {
    for await (const num of mySeq) // No compiler error, since AsyncSequence<T> is an AsyncIterable
}
```
In this example, it seems rather inconvenient having factory methods that upcast to a common interface if we need to downcast later with an assertion. However, note that this is only necessary if you _want_ to iterate the sequence with a `for ... of`/`for await ... of `. This could easily be avoided by using forEach, which is a common interface method and would be prepared to deal with any case:
```ts
const mySeq: Sequence<number> = returnsSomeSequence();

// is it sync? async? we don't care, since either has the
// forEach method, and it is specialized for the class
mySeq.forEach(number => doSomething(number));
```

### Both iterators within `Sequence<T>`
This solution is the one that implies the least amount of code to write (pro: small).
```ts
class Sequence<T> implements Iterable<T>, AsyncIterable<T> { /* ... */ }
```
Similar to the previous approach, this increases the complexity of usage. `Sequence<T>.isAsync(): this is AsyncSequence<T>` and its synchronous sister are necessary again. More dangerously, JavaScript users won't have the safety that the static type checking of the TypeScript compiler provides, although this could be somewhat fixed by throwing errors during runtime if an attempt to asynchronously iterate a synchronous sequence is made (not ideal, really).

I'd like to hear your thoughts about this.

**Comment by k-tten** [comment]
Not giving a fuck is definitely the best way to approach this with least overhead and least cons
I argue that separating async from sync is better for type safety since you do not want to mix async w/ sync and be confused later on

**Comment by AlvinThorn008** [comment]
I'm curious how the AsyncSequence methods would work
```js
const tasks = AsyncSequence.from(["hey", "you're", "a", "real", "stinker"].map(i => Promise.resolve(i)));

tasks.map(task => { // what's the type of task? Promise<string> or string
     //...
})
```

**Comment by k-tten** [comment]
Since it's a lazy sequence, I vouch for methods of the AsyncSequence to be asynchronous. In other words, the impl for the methods could look something like this:
```ts
public async impl(predicate: (v: T) => unknown | Promise<unknown>) {
    // ...
        for await (const v of this) {
            await predicate(v);
        }
    // ...
}
```

However, for AsyncSequence, maybe we should also add implSync, for each impl, like node.js' original fs module, in case a user wants to synchronously loop over promise-likes.

**Comment by maruseron** [comment]
I like the idea of asynchronous methods for AsyncSequence being the preferred way of working with them. ~~A minor caveat is that they imply the necessity of a convenient way of composing multiple intermediate operations, since traditional method chaining wouldn't be available for async methods.~~
```ts
// wrong: public async map<U>(transform: (item: T) => U | Promise<U>): Promise<AsyncSequence<U>>;
// wrong: public async filter<S extends T>(predicate: (item: T) => item is S): Promise<AsyncSequence<S>>;

// AsyncSequence.from(asyncIterable).map(myTransform).filter( /* ... */ )
```
~~Maybe a functional pipe could do the trick:~~
```ts
// public async pipe<?>(...operators: AsyncSequenceOperator<?>[]): Promise<AsyncSequence<?>>;
```
~~The signature of a pipe method seems elusive type-wise, though.~~

**Edit**: forgive my thought lapsus right now, maybe I'm sleep deprived. A pipe is not necessary for intermediate operations because each one of them creates a new Sequence wrapping the original one, making a sort-of generator matryoshka. Async methods would only be necessary for terminal operations which await the composed asynchronous generator; these never return another sequence.

To answer @AlvinThorn08, the callback for `AsyncSequence.map<U>(transform: (item: T, index:? number) => U | Promise<U>): AsyncSequence<U>` would indeed expect a `T`, not a `Promise<T>`. Synchronous promise handling could be done with a synchronous `Sequence`, then `for-await...ing` it.

**Comment by AlvinThorn008** [comment]
@maruseron Thanks for the answer.

**Comment by k-tten** [comment]
Hey what if we made this possible: :trollface: 
```ts
await seq.next();
```

**Comment by maruseron** [comment]
@cursorsdottsx what does that do :notlikethis:

**Comment by k-tten** [comment]
Well it'd basically "lazily" calculate the next item in the sequence

cuz async is lazy... get it :trollface:

**Comment by k-tten** [comment]
Speaking of which... I saw you ask about pipes the other day... Do you plan on adding custom operators and pipes (async pipes???) to sequences?

I finally succeeded in making the typings for "arbitrary arity pipe functions":

[github gist](https://gist.github.com/cursorsdottsx/c4a3ec041a09257b1fa10df7c748aafe)

lmk if you are :)

**Comment by maruseron** [comment]
> Well it'd basically "lazily" calculate the next item in the sequence
> 
> cuz async is lazy... get it :trollface:

That's an interesting proposition. It's currently out of spec, since `Sequence` is stateless and values are currently only calculated through its generator, but it seems like a sensible feature to allow for value "caching", specifically for async generators (seems less useful for materialized asynchronous iterables like a `Promise<T>[]`, since their "calulation" starts as soon as you make them). 

That said, how do you suggest it could be implemented? It seems like that'd be a feature more suitable for a `LazyAsyncIterator` class that wraps an iterator and can freely consume it without worrying about re-iteration.


> Speaking of which... I saw you ask about pipes the other day... Do you plan on adding custom operators and pipes (async pipes???) to sequences?
> 
> I finally succeeded in making the typings for "arbitrary arity pipe functions":
> 
> [github gist](https://gist.github.com/cursorsdottsx/c4a3ec041a09257b1fa10df7c748aafe)
> 
> lmk if you are :)

To answer the custom operators / pipes question: _maybe as another class_. The pipe approach has advantages on its flexibility and extensibility, but it also requires more middleware (pipe -> method -> sink -> new sequence), and seems slightly less performant (in both memory space and throughput) since more allocation/indirection is needed. 
It'd also need an API that makes it easier to extend behavior, since I'm sure no one wants to write the operator along with the Sink it returns and the Sequence subclass returned by the Sink, and after contemplating it for a bit, I don't seem to be able to think of a better solution for stateful intermediate operations other than local anonymous Sequence subclasses, which is rather cursed.

About that gist - holy s**t. That's actually awesome (and would probably kill my TS server).

**Comment by k-tten** [comment]
I made an [updated gist](https://gist.github.com/cursorsdottsx/04a3cd3d5a8ee1532f64e82094f434c8) that works when there is none or one argument present (previously didnt work lol)

Also I opened an issue on RxJS to update the typings (now moved to [discussion](https://github.com/ReactiveX/rxjs/discussions/6671))

And BTW, it doesn't have much impact on TSServer because I use TypeScript 4.5.0-beta with TCO :)

As for my wretched async `next` method that was a joke, I was under the impression that we could just modify `_values`?
Pop off a value from the iterable and replace it?

**Comment by maruseron** [comment]
@cursorsdottsx I have just pushed 0.2.2 with the new AsyncSequence class into both npm and github.

I'll keep exploring the "cached lazy iterator" joke. Sounds interesting. 🤔

**Comment by k-tten** [comment]
Pog. I'll close the issue since we're getting offtopic now 😄
