### ISSUE TITLE
Using object as parameter

### ISSUE THREAD

**Issue by GervinFung** [maruseron/tinylazyseq#2]
Hi Maruseron! What a nice work you have here. I have an idea as I was reading your code, is it possible to group long list of parameters as an object instead?
Example

This
```ts
public join(separator: string, prefix: string, postfix: string, limit: number, truncated: string): string;
```
to This
```ts
public join({
    separator,
    prefix,
    postfix,
    limit,
    truncated
}:{
    separator: string,
    prefix: string,
    postfix: string,
    limit: number,
    truncated: string
}): string;
```
Although this is much lengthier, but I think it would be more usable as the name of the parameters needed are clearly stated as opposed to just passing in the value. Users might not know what values to pass in and what it stands for unless they really look into the definition. Just my 2 cents

**Comment by maruseron** [comment]
Thanks for the feedback! I haven't given the join function a lot of usage, so this is something I had not thought about previously. Looking back, it is pretty limitting that unwanted arguments must be provided in order to reach the desired one. I'm certainly doing this change for the next version.

**Comment by GervinFung** [comment]
Thanks for your reply! In that case there's a possibility that some of the functions will need to use object as parameters as well. If there's any help needed, please let me know

**Comment by maruseron** [comment]
Mind sharing your thoughts about which other functions could use object parameters instead of their current state?

**Comment by k-tten** [comment]
<img width="1061" alt="Screen Shot 2021-11-06 at 18 38 58" src="https://user-images.githubusercontent.com/65373746/140626963-9fabcebc-e4bb-424d-8389-3b21fd66a23c.png">
i dont think this is necessary

**Comment by maruseron** [comment]
True. I changed the signature of join in the dev branch I haven't pushed into git to the following:
```ts
public join(): string;
public join(options: { 
    separator?: string,
    prefix?: string,
    postfix?: string,
    limit?: number, 
    truncated?: string,
    transform?: (item: T) => string
}): string;
public join(options?: { 
    separator?: string, 
    prefix?: string, 
    postfix?: string, 
    limit?: number, 
    truncated?: string,
    transform?: (item: T) => string
}): string { /* ... */ }
```

**Comment by GervinFung** [comment]
> Mind sharing your thoughts about which other functions could use object parameters instead of their current state?

Although not exactly that critical compared to that of `join`, I would say the function below
```ts
public static generate<T>(initial: T, nextValue: (current: T) => T | null): Sequence<T>
public fold<R>(initial: R, operation: (accumulator: R, current: T) => R): R 
```
Although it's still understandable, somehow I think it's still better to be used as object to know what the initial and function stands for

So in this case, the second one is definitely more declarative than the first one
and the reason is that there is a name for it
```ts
//1st
const sum = () => fold((sum, val) => sum + val, 0);
//2nd
const add = (sum, val) => sum + val
const initialValue = 0
const sum = () => fold(add, initialValue);
```

But since most people would not write the code like the example above as it's optional to name a function / variable and pass it as parameters
So the example below would be much more self-explanatory
```ts
const sum = () => fold({
    add: (sum, val) => sum + val,
    initialValue: 0
});
```
Again. that's my 2 cents :)

**Comment by maruseron** [comment]
@GervinFung I think "not as critical" is an understatement for how trivial these cases are, to the point I disagree for this particular case. `generate` and `fold` are common terms for infinite sequence generation and reduction with initial values respectively, as seen in the following examples:

### Generate (aka Create or Iterate)
- Kotlin: [kotlin.sequences.generateSequence](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.sequences/generate-sequence.html)
- Java: [java.util.Stream.generate / java.util.Stream.iterate](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#generate-java.util.function.Supplier-)
- RxJS: [rxjs.generate](https://rxjs.dev/api/index/function/generate)
- Spring Reactor: [reactor.core.publisher.Flux.generate](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#generate-java.util.concurrent.Callable-java.util.function.BiFunction-)

### Fold (aka Aggregate, Reduce, Accumulate)
- Kotlin: [kotlin.sequences.Sequence.fold](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.sequences/fold.html)
- Haskell, Elixir, Elm, Erlang and 80? other FP languages: [foldl (link is Haskell docs)](https://wiki.haskell.org/Fold)
- Rust: [std.iter.Iterator.fold](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.fold)
- F#: [List.fold](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-listmodule.html#fold)
- Haxe: [Lambda.fold](https://api.haxe.org/Lambda.html#fold)

Maybe there's a case for more specific naming (something like `generateFrom` or `generateFromSeed` instead of `generate`) but, as they are now, I don't think they're prone to cause any confusion in any decently competent IDE.

**Comment by GervinFung** [comment]
> @GervinFung I think "not as critical" is an understatement for how trivial these cases are, to the point I disagree for this particular case. `generate` and `fold` are common terms for infinite sequence generation and reduction with initial values respectively, as seen in the following examples:
> ### Generate (aka Create or Iterate)
> 
>     * Kotlin: [kotlin.sequences.generateSequence](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.sequences/generate-sequence.html)
> 
>     * Java: [java.util.Stream.generate / java.util.Stream.iterate](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#generate-java.util.function.Supplier-)
> 
>     * RxJS: [rxjs.generate](https://rxjs.dev/api/index/function/generate)
> 
>     * Spring Reactor: [reactor.core.publisher.Flux.generate](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#generate-java.util.concurrent.Callable-java.util.function.BiFunction-)
> 
> 
> ### Fold (aka Aggregate, Reduce, Accumulate)
> 
>     * Kotlin: [kotlin.sequences.Sequence.fold](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.sequences/fold.html)
> 
>     * Haskell, Elixir, Elm, Erlang and 80? other FP languages: [foldl (link is Haskell docs)](https://wiki.haskell.org/Fold)
> 
>     * Rust: [std.iter.Iterator.fold](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.fold)
> 
>     * F#: [List.fold](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-listmodule.html#fold)
> 
>     * Haxe: [Lambda.fold](https://api.haxe.org/Lambda.html#fold)
> 
> 
> Maybe there's a case for more specific naming (something like `generateFrom` or `generateFromSeed` instead of `generate`) but, as they are now, I don't think they're prone to cause any confusion in any decently competent IDE.

I agree with you on that. Thank you for pointing the references as well

**Comment by maruseron** [comment]
0.2.2 has shipped with the new `join` method signature getting an options object. Closing this since the issue has been addressed.
